import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {collectConnectedUsage,decodeHostAction} from '../connected-terminal-host.mjs';
import {encodeAction,decodeAction} from '../usage-terminal.mjs';
const options=terminal=>({terminal,workspace:'C:\\approved-empty',sourceDirectory:'C:\\source',confirmDisplayOnly:true,confirmPreviouslyTrustedWorkspace:true});
function fake({early=false,echo=true,duplicate=false,stuck=false}={}){
 const calls=[],frames=[{action:'write',text:'/usage\r'},duplicate?{action:'write',text:'/usage\r'}:{action:'exit-own-session',texts:['\u001b','/exit\r'],result:{provider:'claude',routerAuthorized:false,privateHeader:'private-user',pools:[{pool:'native-all-models',windows:[{name:'session',remainingPercent:40,quantitySource:{kind:'used',value:60,operation:'100-minus-used'},reset:{kind:'time-only',display:'Resets 3pm private-user'}}]}]}}];
 return {calls,async exec({cmd}){if(cmd.includes('Get-Item'))return {output:'{"empty":true,"reparse":false}',exit_code:0};if(cmd.includes('usage-preflight'))return {output:'{"ready":true}',exit_code:0};if(cmd.includes('usage-terminal'))return {session_id:11,output:encodeAction({action:'start-approved-pty',provider:'claude',rawInputEchoDisabled:echo})};return {session_id:22,output:'',...(early?{exit_code:1}:{})};},async exchange({session_id,chars}){calls.push([session_id,chars]);if(session_id===11){if(chars.includes('"output"'))return {output:encodeAction(early?{action:'close-own-session',result:{reason:'cli_exited_before_panel'}}:frames.shift()),...(frames.length===0?{exit_code:0}:{})};return {exit_code:0,output:''};}if(session_id!==22)throw Error('unowned');return {output:'',...(!stuck&&(chars==='/exit\r'||chars==='\u0003')?{exit_code:0}:{})};}};
}
test('portable decoder preserves UTF-8 and ignores terminal control noise',()=>assert.deepEqual(decodeHostAction('\u001b[2J'+encodeAction({value:'日本語'})),{value:'日本語'}));
test('host reconstructs allowlisted result and closes only owned sessions',async()=>{const t=fake(),r=await collectConnectedUsage('claude',options(t));assert.equal(r.collection.usageCommands,1);assert.equal(r.routerAuthorized,false);assert.equal(r.pools[0].windows[0].reset.display,null);assert.ok(!JSON.stringify(r).includes('private-user'));assert.ok(t.calls.every(([id])=>[11,22].includes(id)));assert.ok(Object.values(r.collection.cleanup).every(Boolean));});
test('natural early exit is not mistaken for failed cleanup',async()=>{const r=await collectConnectedUsage('claude',options(fake({early:true})));assert.equal(r.reason,'cli_exited_before_panel');});
test('second usage write never executes',async()=>{const t=fake({duplicate:true}),r=await collectConnectedUsage('claude',options(t));assert.equal(r.reason,'invalid_protocol_action');assert.equal(t.calls.filter(([id,c])=>id===22&&c==='/usage\r').length,1);});
test('non-TTY protocol cannot assert disabled echo',()=>{const p=spawnSync(process.execPath,['usage-terminal.mjs','--provider','claude'],{input:'',encoding:'utf8',timeout:5000});assert.equal(decodeAction(p.stdout).rawInputEchoDisabled,false);});
test('host rejects missing echo protection before provider launch',async()=>{const t=fake({echo:false}),r=await collectConnectedUsage('claude',options(t));assert.equal(r.reason,'protocol_start_failed');assert.ok(!t.calls.some(([id])=>id===22));});
test('unconfirmed owned cleanup blocks and discards measurements',async()=>{const r=await collectConnectedUsage('claude',options(fake({stuck:true})));assert.equal(r.reason,'cleanup_unconfirmed');assert.equal(r.pools,undefined);});
test('cancellation before start launches nothing',async()=>{let calls=0;const r=await collectConnectedUsage('claude',{...options({exec(){calls++;},exchange(){calls++;}}),signal:{aborted:true}});assert.equal(r.reason,'collection_canceled');assert.equal(calls,0);});
